"""renamed text -> column to avoid any confusion

Revision ID: 615b576317e6
Revises: 5c3da124ee29
Create Date: 2025-07-24 13:55:43.849527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615b576317e6'
down_revision: Union[str, None] = '5c3da124ee29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_table', sa.Column('comment', sa.Text(), nullable=False))
    op.drop_column('log_table', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_table', sa.Column('text', sa.TEXT(), nullable=False))
    op.drop_column('log_table', 'comment')
    # ### end Alembic commands ###
