"""add mood_color column

Revision ID: cb3ea58ace36
Revises: ed408d7d5dcd
Create Date: 2025-07-24 11:53:59.517501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3ea58ace36'
down_revision: Union[str, None] = 'ed408d7d5dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_table', sa.Column('mood_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_table', 'mood_color')
    # ### end Alembic commands ###
